### ISSUE TITLE
grunt connect本地启动后，为什么会报错。

### ISSUE THREAD

**Issue by btea** [sealtalk/sealtalk-web#10]
Running "connect:server" (connect) task
Waiting forever...
Fatal error: Port 80 is already in use by another process.

（以上是错误信息，明明使用的8181端口，为何会报错80端口）

**Comment by shuise** [comment]
Gruntfile.coffee 查查这里的配置是否还有没调整端口的

**Comment by btea** [comment]
谢谢，已经改过来了。
请问下载下来之后本地测试登录的话，需要连接数据库吗？应该怎么连接？

**Comment by YongHao0** [comment]
1. web 不需要链接数据库
2. web 使用的前提是启动 sealtalk server, server 需要连接 mysql 数据库
    具体见 server 源码及说明: https://github.com/sealtalk/sealtalk-server
