### ISSUE TITLE
登录页登录的时候报错405，是怎么回事？

### ISSUE THREAD

**Issue by btea** [sealtalk/sealtalk-web#11]
网页版登录的时候，是要连接数据库吗？能链接融云呃数据库吗？要怎么设置连接呢？

**Comment by shuise** [comment]
项目readme最后部分有说明

**Comment by btea** [comment]
那个说明我有看到，不过对于后台数据库服务器这部分我很陌生，按照下面给的那个连接说明，还是要在本地装一个mysql再进行配置？

**Comment by shuise** [comment]
https://github.com/sealtalk/sealtalk-server 项目有相应说明，照着文档处理即可
