### ISSUE TITLE
群组发布公告bug

### ISSUE THREAD

**Issue by Fourleafclove** [sealtalk/sealtalk-web#15]
在没有群组对话的前提下，比如刚创建完群组而没有发起会话时，发布一次群组公告再发起群组会话会在获取draftMsg的时候报错，消息没法发送，setDraft也会一直报错

**Comment by shuise** [comment]
setDraft应该是纯本地操作，获取draft报错的根本原因是什么？

**Comment by Fourleafclove** [comment]
<img width="767" alt="wx20170808-093054 2x" src="https://user-images.githubusercontent.com/15857976/29052386-4f9b534a-7c1c-11e7-8654-b1bf5f610182.png">
报的错是这样的，我试了下官网的sealtalk-web也有这样的问题

**Comment by shuise** [comment]
这个代码确实已经通知更新有一段时间了，第一个错误里有null，第二个错误提示里有第二个参数有错误，请排查定位一下。
