### ISSUE TITLE
本地不可登录实现

### ISSUE THREAD

**Issue by btea** [sealtalk/sealtalk-web#16]
按照相关说明配置完成之后，在登录页输入已经注册过的账号密码登录失败，报错405或者500。本地web项目是要直接链接融云的服务器还是本地clone server代码之后进行相应配置，前者是如何操作？后者的话，server端和web端又是如何具体进行联系的？web版的资料网上也很少，请详细描述一下，谢谢！

**Comment by shuise** [comment]
项目主页最下方有部署说明
