### ISSUE TITLE
http://api.sealtalk.im/user/zj3AqojRy

### ISSUE THREAD

**Issue by slowsay** [sealtalk/sealtalk-web#18]
在源码中，request headers 哪里设置了cookies?

**Comment by shuise** [comment]
cookie是自动带上的，不需要手工处理，只需要让server和web同处于一个父域下即可。
你可以在sealtalk在线体验里抓包看看 http://web.sealtalk.im/

**Comment by slowsay** [comment]
嗯，是的，谢了
