### ISSUE TITLE
RongIMClient.registerMessageType

### ISSUE THREAD

**Issue by slowsay** [sealtalk/sealtalk-web#20]
RongIMClient.registerMessageType(messageName,objectName,mesasgeTag,propertys);

bug
----------------------------------------------------------------------------
Uncaught TypeError: Cannot read property 'msgTag' of undefined  VM1474:1 

msgTag这个应该是框架里输出的，
自定义事件与原有事件，形式不太一样，输出的事件是messagetype:textmessage
而自定义事件输出却是messagetype:{message:selfmessage}

**Comment by YongHao0** [comment]
此问题已解决, 参考最新版 SealTalk Web: https://github.com/sealtalk/sealtalk-web
