### ISSUE TITLE
本地运行为什么打不开？？

### ISSUE THREAD

**Issue by silence-may** [sealtalk/sealtalk-web#21]
运行grunt connect后，打开的页面显示Cannot GET /，请问该怎么做啊？？

**Comment by shuise** [comment]
readme里是一个严格测试过的流程，请严格逐步处理，估计是没有部署 appserver 吧

**Comment by silence-may** [comment]
感谢您的回复，sealtalk-web是需要部署sealtalk-server的是吗？？以sealtalk-server为后端是吗？？

**Comment by shuise** [comment]
请按照文档逐步操作，每步都有说明，sealtalk-server有链接，项目里有文档说明

**Comment by jeans8090** [comment]
运行grunt connect后，一直提示：
Running "connect:server" (connect) task
Waiting forever...
Started connect web server on http://localhost:8181
然后页面也是Cannot GET /
请问大佬，这个怎么解决啊
