### ISSUE TITLE
完全按照READ来的,为什么没有启动起来呢,谢谢

### ISSUE THREAD

**Issue by zhangenming** [sealtalk/sealtalk-web#22]
<img width="1549" alt="screenshot" src="https://user-images.githubusercontent.com/21235555/35379486-2c7251ce-01f1-11e8-83b3-bde28b1cba38.png">

- 左面是grunt build
- 右面是服务器端的grunt nodemon(服务器端README少npm i这个步骤)
- 中间的grunt connect失败
- 最上面是修改的配置文件

谢谢

而且README里面下面这行是错的
`修改配置，配置文件/src/assets/app.config`
文件路径应该这个吧
 `/src/app.config`

谢谢

**Comment by YongHao0** [comment]
grunt connect 启动端口失败, 需要确定 80 端口是否被其他程序占用
另外, 不执行 grunt connect, 直接访问 build/index.html 也可访问页面(需使用 http 协议)
