### ISSUE TITLE
app server如何获取

### ISSUE THREAD

**Issue by zhangsenrong** [sealtalk/sealtalk-web#25]
我直接把dist目录放到tomcat下，不可以吗？app server是我自己应用的服务器吗

**Comment by shuise** [comment]
sealtalk-web项目首页有写 app server 的链接信息
dist是编译完的代码，放在任意 webserver 都可以

**Comment by zhangsenrong** [comment]
你好，感谢你的回复，项目按照说明已经跑起来了，现在的问题是，app server 是真的没有找到，浏览器上就一个登陆界面，没有任何的链接，index.html代码也看了，里面也没有，如果APP server是固定的，能否直接给我一个，如果是动态的，能否详细说一下如何获取。非常感谢。

**Comment by shuise** [comment]
页面：https://github.com/sealtalk/sealtalk-web/
内容复制：
appkey: 从融云注册的应用 key，注册地址：https://developer.rongcloud.cn/signup
serverUrl: App Server 地址，使用 https://github.com/sealtalk/sealtalk-server 部署后获取
