### ISSUE TITLE
加对方为好友时，对方的页面没能立即出现提示，刷新页面才出现

### ISSUE THREAD

**Issue by henankeer** [sealtalk/sealtalk-web#28]
如题，加对方为好友时，对方的页面没能立即出现提示，刷新页面才出现。给对方发消息，都是可以立即出现的，唯独加好友不能，这个怎么改呢？

**Comment by yuhongda0315** [comment]
可排查下收到加好友通知消息后，是否更新了 UI，可在消息监听 onReceived 中设置断点逐步跟进
