### ISSUE TITLE
grunt build,出现error，什么原因？

### ISSUE THREAD

**Issue by yongpeixu** [sealtalk/sealtalk-web#3]
$ grunt build
Running "clean:build" (clean) task

> > 3 paths cleaned.

Running "copy:build" (copy) task
Created 2 directories, copied 62 files

Running "concat:build" (concat) task
File ./build/assets/js/angular-widget.min.js created.
File ./build/assets/js/other.min.js created.
File ./build/assets/css/main.css created.

Running "typescript:build" (typescript) task

> > src/assets/lib/RongIMlib.d.ts(1624,14): error TS1005: ';' expected.
> > src/assets/lib/RongIMlib.d.ts(1628,18): error TS1005: '=' expected.
> > src/assets/lib/RongIMlib.d.ts(1628,26): error TS1005: ';' expected.
> > src/assets/lib/RongIMlib.d.ts(1630,14): error TS1005: ';' expected.
> > src/assets/lib/RongIMlib.d.ts(1632,14): error TS1005: ';' expected.
> > Warning: Task "typescript:build" failed. Use --force to continue.

Aborted due to warnings.

**Comment by yujun2013** [comment]
请问现在正常了吗

**Comment by Night-Kang** [comment]
明显没有

**Comment by hwswin** [comment]
另外一个项目（https://github.com/rongcloud/rongcloud-web-im-sdk-v2/tree/master）
出现和你同样的问题。这个项目倒是可以正常编译启动

**Comment by YongHao0** [comment]
问题已解决, 按最新文档运行即可
