### ISSUE TITLE
依赖库安装失败

### ISSUE THREAD

**Issue by Astaca** [sealtalk/sealtalk-web#30]
运行tsd install 这一环节报错
The type definition `index.d.ts` does not exist. Create one and try again.

**Comment by YongHao0** [comment]
代码已更新, 重新拉取代码, 按照文档编译即可

**Comment by jeans8090** [comment]
重新拉代码也还是不行啊，请问下报这个错应该怎么解决

**Comment by YongHao0** [comment]
> 重新拉代码也还是不行啊，请问下报这个错应该怎么解决

您重拉代码后, 不执行 tsd install 再试下

**Comment by jeans8090** [comment]
本地启动服务之后 

grunt connect​​ 一直显示
Running "connect:server" (connect) task
Waiting forever..​​
然后页面空白的，项目跑不起来啊，
还望大佬指教指教


------------------ 原始邮件 ------------------
发件人: "YongHao0"<notifications@github.com>;
发送时间: 2019年9月23日(星期一) 中午12:00
收件人: "sealtalk/sealtalk-web"<sealtalk-web@noreply.github.com>;
抄送: "潇湘夜雨"<794033356@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [sealtalk/sealtalk-web] 依赖库安装失败 (#30)



 
重新拉代码也还是不行啊，请问下报这个错应该怎么解决
  
您重拉代码后, 不执行 tsd install 再试下
