### ISSUE TITLE
您好，我 部署了 sealtalk和sealtalk-web，登录 是可以成功的，但是我登录进来之后 全部出现403接口拒绝？这是什么原因呢？搞了好久了，实在搞不定node了

### ISSUE THREAD

**Issue by angeless-jacky** [sealtalk/sealtalk-web#32]
![image](https://user-images.githubusercontent.com/53263329/61794089-0b807f80-ae53-11e9-8771-f6dc874ae873.png)
![image](https://user-images.githubusercontent.com/53263329/61794136-1c30f580-ae53-11e9-9e7f-5ddea4d0bda2.png)

![image](https://user-images.githubusercontent.com/53263329/61794163-218e4000-ae53-11e9-9179-8bf087212ca3.png)
dalao大佬能告诉一下原因?望指点一下

**Comment by Jasonmin** [comment]
你这个融云的服务用的是自己的服务器吧？那项目里的http接口也要更新成自己的

**Comment by YongHao0** [comment]
检查下您的 sealtalk server conf.js 的配置
必须保证 conf.js AUTH_COOKIE_DOMAIN 选项正确
比如 server 站点为: api.sealtalk.im, 则 AUTH_COOKIE_DOMAIN 必须为: sealtalk.im

**Comment by sduqlsc** [comment]
没有域名的只有IP，`AUTH_COOKIE_DOMAIN`这里应该怎么填写？ @YongHao0

**Comment by sduqlsc** [comment]
有人在吗？

**Comment by YongHao0** [comment]
没有域名, 只有 IP 的话
AUTH_COOKIE_DOMAIN 填入 ip 地址即可
