### ISSUE TITLE
grund build卡住不动，启动不了项目

### ISSUE THREAD

**Issue by Moonsyf** [sealtalk/sealtalk-web#33]
[
![image](https://user-images.githubusercontent.com/44771941/62268997-45114600-b464-11e9-8053-be4b77f45ab9.png)
](url)

**Comment by Jasonmin** [comment]
这个不用管，编译完成之后会生成一个build目录，你把bulid里的项目启动就可以了

**Comment by YongHao0** [comment]
waiting 状态说明已编译成功, 此时您启动 build 目录中的 index.html 即可
