### ISSUE TITLE
运行提示如下错误是为什么啊

### ISSUE THREAD

**Issue by Alisa0585** [sealtalk/sealtalk-web#37]
Uncaught Error: [$injector:modulerr] Failed to instantiate module webim due to:
Error: [$injector:modulerr] Failed to instantiate module ui.router due to:
Error: [$injector:nomod] Module 'ui.router' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by YongHao0** [comment]
检查下您的运行步骤, 查看是否正确执行了
npm install
bower install
