### ISSUE TITLE
web 对应的appkey是哪一个

### ISSUE THREAD

**Issue by chuan-T** [sealtalk/sealtalk-web#38]
此处填写您的融云 AppKey 
这个appkey是这个吗
![image](https://user-images.githubusercontent.com/43464580/71662088-3f10ef80-2d8b-11ea-8b51-ff2841427259.png)

**Comment by ericyangpan** [comment]
> 此处填写您的融云 AppKey
> 这个appkey是这个吗
> ![image](https://user-images.githubusercontent.com/43464580/71662088-3f10ef80-2d8b-11ea-8b51-ff2841427259.png)

Yes
