### ISSUE TITLE
是我的操作不对，还是你们的文档有错误？？？

### ISSUE THREAD

**Issue by 8debug** [sealtalk/sealtalk-web#40]
![image](https://user-images.githubusercontent.com/3394927/91145603-4f922380-e6e8-11ea-9265-7d19e33af040.png)
 执行完这步以后点击index.html报如下错误：

![image](https://user-images.githubusercontent.com/3394927/91145695-751f2d00-e6e8-11ea-8239-ad397a1286ad.png)

**Comment by congk** [comment]
文档描述有歧义，应该是"以 Http 协议通过浏览器打开指定 html 文件"，看截图中错误信息中用的是 file 协议
这里需要启一个 Web 服务用来托管待加载的静态资源
